Repository Banal972/dallaem_refactoring, pull requests merged in 2024-09, with the labels that each got.

#5 Feat : 로그인 로직 수정
  package-lock.json
  package.json
  src/app/api/auth/[...nextauth]/route.ts
  src/app/auth/@signin/page.tsx
  src/app/auth/@signup/page.tsx
  src/app/auth/page.tsx
  src/app/layout.tsx
  src/auth.ts
  src/components/public/gnb/GNB.tsx
  src/components/public/gnb/components/ProfileComponent.tsx
  src/types/auth/auth.d.ts
Labels: refactoring, Feat

#8 fix : get cookie 수정
  src/actions/Auths/editProfileInfo.ts
  src/actions/Auths/getUserInfo.ts
  src/actions/Gatherings/cancelMeeting.ts
  src/actions/Gatherings/fetchMyPageInfo.ts
  src/actions/Gatherings/generateGathering.ts
  src/actions/Gatherings/joinGathering.ts
  src/actions/Gatherings/quitMeeting.ts
  src/actions/Reviews/addReview.ts
  src/actions/Reviews/getAllReviews.ts
  src/components/pages/mainpage/ReviewPreview.tsx
  src/middleware.ts
Labels: Fix

#7 #2 profile edit btn my page info tap use tap hook hook 분리 및 오류 수정
  .eslintrc.json
  package-lock.json
  package.json
  src/components/pages/mypage/MyPageInfoTap.tsx
  src/components/pages/mypage/UnderBar.tsx
  src/components/public/ProfileEditBtn.tsx
  src/components/public/img/ProfileBG.tsx
  src/hooks/mypage/useTapHook.ts
Labels: Bug, refactoring, chore

#9 feat : 로그인 UI 변경 및 애니메이션 추가
  src/app/layout.tsx
  src/components/app/RouteValidationLayout.tsx
  src/components/pages/auth/LoginModal.tsx
  src/components/public/gnb/GNB.tsx
  src/components/public/gnb/components/ProfileComponent.tsx
  src/middleware.ts
Labels: refactoring, Feat

#11 Feat : 회원가입 로직 변경
  src/actions/Auth-actions/signup.ts
  src/components/pages/auth/@signin/SigninForm.tsx
  src/components/pages/auth/@signin/Validations.ts
  src/components/pages/auth/@signup/SignupForm.tsx
  src/components/pages/auth/@signup/Validations.ts
  src/components/pages/auth/AuthArticle.tsx
  src/components/pages/auth/AuthModal.tsx
  src/components/pages/auth/LoginModal.tsx
  src/components/pages/auth/Modal/Atoms/Input.tsx
  src/components/pages/auth/Modal/Atoms/VerifyBtn.tsx
  src/components/pages/auth/Modal/CompleteSignUpModal.tsx
  src/components/pages/auth/Modal/LoginModal.tsx
  src/components/pages/auth/Modal/SignUpModal.tsx
  src/components/public/gnb/components/ProfileComponent.tsx
  src/constants/Regex.ts
  src/hooks/Auth/usePostSignup.tsx
  src/types/auth/auth.d.ts
Labels: refactoring, Feat

#12 #10 마이페이지 나머지 rcc hook 분리
  src/components/pages/mypage/MyPageInfoWrapper.tsx
  src/components/pages/mypage/SkeletonWrapper.tsx
  src/components/public/ProfileEditBtn.tsx
  src/hooks/useNav.ts
Labels: refactoring

#15 Feat : 로그인 에러 헨들링
  src/app/layout.tsx
  src/auth.ts
  src/components/app/RouteValidationLayout.tsx
  src/components/pages/auth/AuthModal.tsx
  src/components/pages/auth/Modal/LoginModal.tsx
  src/components/public/gnb/GNB.tsx
  src/components/public/gnb/Profile/Atoms/Authenticated.tsx
  src/components/public/gnb/Profile/Atoms/NotAuthenticated.tsx
  src/components/public/gnb/Profile/Profile.tsx
  src/components/public/gnb/SideBar/Atoms/SideBarBtn.tsx
  src/components/public/gnb/SideBar/SideBar.tsx
Labels: refactoring, Feat

#19 refactor : RCC Hook 분리
  src/components/pages/wishlist/List.tsx
  src/hooks/useWishList.tsx
Labels: refactoring

#21 refactor : 리뷰 페이지 rcc hook 분리
  src/components/pages/allReview/List.tsx
  src/components/pages/allReview/Scores/Atoms/RatingBar.tsx
  src/components/pages/allReview/Scores/Scores.tsx
  src/components/pages/mainpage/MainReview.tsx
  src/hooks/Review/useAllReview.tsx
  src/hooks/Review/useScoreCalculation.tsx
Labels: refactoring, Fix

#18 fix : middleware 오류 수정
  src/actions/Auths/onLogout.ts
  src/actions/Auths/postSigninFn.ts
  src/actions/Auths/postSignupFn.ts
  src/auth.ts
  src/components/pages/auth/Modal/LoginModal.tsx
  src/components/public/LogoutBtn.tsx
  src/components/public/gnb/Profile/Atoms/Authenticated.tsx
  src/hooks/usePostSignin.tsx
  src/hooks/usePostSignup.ts
  src/middleware.ts
Labels: Bug, Fix

#20 #17 icon및 텍스트 이탈 버그 수정
  src/components/pages/mainpage/MainReview.tsx
  src/components/public/ProfileBox.tsx
  src/components/public/ProfileEditBtn.tsx
Labels: Bug

#23 refactor : onFilterChanged 공용으로
  src/app/findMeeting/page.tsx
  src/components/pages/allReview/List.tsx
  src/components/pages/allReview/Scores/Scores.tsx
  src/components/pages/wishlist/List.tsx
  src/util/onFilterChanged.ts
Labels: refactoring

#24 refactor : 로그인 체크 수정 및 로직 수정
  src/actions/Auths/checkLogin.ts
  src/actions/Auths/getUserTokenFromCookieFn.ts
  src/app/findMeeting/page.tsx
  src/auth.ts
  src/components/pages/auth/Modal/LoginModal.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingList/MeetingList.tsx
  src/components/pages/wishlist/WishBtn.tsx
  src/components/public/bottomFloatingBar/BottomFloatingBar.tsx
  src/components/public/gnb/GNB.tsx
  src/components/public/gnb/Profile/Atoms/Authenticated.tsx
  src/components/public/gnb/Profile/Profile.tsx
  src/hooks/useUserToken.ts
  src/util/useGNBLogic.ts
Labels: refactoring, Fix

#27 #26 mypage 버그 확인
  src/actions/Gatherings/cancelJoining.ts
  src/components/pages/mypage/MyPageInfoWrapper.tsx
  src/components/public/Card/Atom/CardBtn.tsx
  src/components/public/ProfileBox.tsx
Labels: Bug, refactoring

#29 #28 findmeeting page.tsx 훅 분리
  src/app/findMeeting/[slug]/page.tsx
  src/app/findMeeting/page.tsx
  src/types/findMeeting/findMeeting.d.ts
Labels: refactoring

#31 #30 findmeeting page 컴포넌트 분리
  src/app/allReview/page.tsx
  src/app/findMeeting/page.tsx
  src/app/wishlist/page.tsx
  src/components/pages/findMeeting/CreateMeetingBtn.tsx
  src/components/pages/findMeeting/FilterTaps.tsx
  src/components/public/ImageHeader.tsx
  src/types/common/global.d.ts
  src/types/findMeeting/findMeeting.d.ts
Labels: refactoring

#32 13 toast 방식 수정
  src/app/callback/page.tsx
  src/app/findMeeting/page.tsx
  src/app/layout.tsx
  src/components/pages/auth/Modal/LoginModal.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingList/MeetingList.tsx
  src/components/pages/wishlist/WishBtn.tsx
  src/components/public/Toast.tsx
  src/components/public/bottomFloatingBar/BottomFloatingBar.tsx
  src/components/public/gnb/Profile/Atoms/Authenticated.tsx
  src/hooks/useNav.ts
  src/middleware.ts
  src/provider/ToastProvider.tsx
Labels: Bug, refactoring, Fix

#35 #34 hydrationboundary custom hook으로 분리
  src/app/(MyPage)/mypage/page.tsx
  src/hooks/CustomHydrationBoundary.tsx.tsx
Labels: refactoring

#36 성능 60%로 나오는 문제 해결법 #33
  package-lock.json
  package.json
  src/app/findMeeting/page.tsx
  src/components/pages/allReview/FilterSort.tsx
  src/components/pages/allReview/Scores/Scores.tsx
  src/components/pages/findMeeting/FilterCalendar/FilterCalendar.tsx
  src/components/pages/findMeeting/FilterSort/FilterSort.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingList/MeetingList.tsx
  src/components/pages/mainpage/Banner.tsx
  src/components/pages/mainpage/MainReview.tsx
  src/components/pages/mainpage/NewMeeting.tsx
  src/components/public/Card/Card.tsx
  src/components/public/Card/MyCard/MyCard.tsx
  src/components/public/Filter/Filter.tsx
  src/components/public/ImageHeader.tsx
  src/components/public/ProfileBox.tsx
  src/components/public/ProfileEditBtn.tsx
  src/components/public/img/Profile.tsx
  src/components/public/img/ProfileBG.tsx
Labels: refactoring

#40 #39 mypage type 파일 재정리
  src/app/(MyPage)/mypage/page.tsx
  src/components/pages/mypage/MyPageDefault.tsx
  src/components/public/ProfileBox.tsx
  src/components/public/img/ProfileBG.tsx
  src/hooks/CustomHydrationBoundary.tsx.tsx
  src/hooks/mypage/CustomHydrationBoundary.tsx.tsx
  src/types/mypage/mypage.d.ts
Labels: refactoring

#41 README.md 작성
  README.md
Labels: chore

#44 refactor : 메인 페이지, 찜목록, 리뷰페이지 qa 및 타입 정리
  __mocks__/svgrMock.jsx
  src/app/page.tsx
  src/components/pages/allReview/FilterSort.tsx
  src/components/pages/findMeeting/CreateMeeting/CreateMeetingForm.tsx
  src/components/pages/findMeeting/CreateMeeting/selectComponents/SelectServiceButton.tsx
  src/components/pages/findMeeting/FilterCalendar/FilterCalendar.tsx
  src/components/pages/findMeeting/FilterTab/FilterTab.tsx
  src/components/pages/findMeeting/FilterTaps.tsx
  src/components/pages/mainpage/MainReview.tsx
  src/components/pages/mainpage/NewMeeting.tsx
  src/components/pages/wishlist/ByeBtn.tsx
  src/components/pages/wishlist/List.tsx
  src/components/public/Calendars/Calendars.tsx
  src/components/public/Card/Card.tsx
  src/components/public/Card/MyCard/MyCard.tsx
  src/components/public/CloseBtn.tsx
  src/components/public/Filter/Filter.tsx
  src/components/public/ProfileBox.tsx
  src/components/public/Review/Review.tsx
  src/components/public/Review/ReviewHeartBtn/ReviewHeartBtn.tsx
  src/components/public/icon/dynamicIcon/Arrow.tsx
  src/components/public/icon/dynamicIcon/Checkbox.tsx
  src/components/public/icon/dynamicIcon/Heart.tsx
  src/components/public/icon/dynamicIcon/Save.tsx
  src/components/public/icon/dynamicIcon/Sort.tsx
  src/components/public/icon/staticIcon/Alarm.tsx
  src/components/public/icon/staticIcon/ArrowRight.tsx
  src/components/public/icon/staticIcon/Bye.tsx
  src/components/public/icon/staticIcon/Check.tsx
  src/components/public/icon/staticIcon/Dalaemfit.tsx
  src/components/public/icon/staticIcon/Edit.tsx
  src/components/public/icon/staticIcon/MenuIcon.tsx
  src/components/public/icon/staticIcon/Person.tsx
  src/components/public/icon/staticIcon/VisibilityOff.tsx
  src/components/public/icon/staticIcon/VisibilityOn.tsx
  src/components/public/icon/staticIcon/Workation.tsx
  src/components/public/icon/staticIcon/X.tsx
  src/components/public/img/Edit.tsx
  src/components/public/img/Head.tsx
  src/components/public/img/ImgLogin.tsx
  src/components/public/img/Logo.tsx
  src/components/public/img/Profile.tsx
  src/components/public/input/InputField.tsx
  src/components/public/input/components/Dropdown.tsx
  src/components/public/modal/CreateMeetingModal.tsx
  src/components/public/modal/ProfileEditModal.tsx
Labels: refactoring

#45 refactor: Provider 정리
  src/app/layout.tsx
Labels: refactoring

#47 refactor : 메인페이지 타입 정리
  src/components/pages/auth/AuthModal.tsx
  src/components/pages/auth/Modal/CompleteSignUpModal.tsx
  src/components/pages/auth/Modal/LoginModal.tsx
  src/components/pages/auth/Modal/SignUpModal.tsx
  src/components/pages/mainpage/Banner.tsx
  src/components/pages/mainpage/HeadContent.tsx
  src/components/pages/mainpage/MainReview.tsx
  src/components/pages/mainpage/NewMeeting.tsx
  src/types/auth/auth.d.ts
  src/types/main/main.d.ts
Labels: refactoring

#49 #46 cypress 설정 변경 및 테스트 코드 확인
  .eslintignore
  .github/workflows/dispatch.yaml
  .github/workflows/test.yaml
  .github/workflows/trigger-dispatch.yaml
  cypress/e2e/gnb.cy.ts
  cypress/e2e/home.cy.ts
  cypress/e2e/logIn.cy.ts
  cypress/e2e/mypage.cy.ts
  cypress/e2e/signup.cy.ts
  cypress/e2e/wishlist.cy.ts
  cypress/support/commands.ts
  cypress/tsconfig.json
  jest.config.js
  package-lock.json
  package.json
  src/components/pages/mainpage/MainReview.tsx
  tsconfig.json
Labels: Fix
